<?php

namespace Infrastructure\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Domain\App\Repository\ArticleRepositoryInterface;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository implements ArticleRepositoryInterface
{
}
